## MNIST Classification using CNN

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml

In [10]:
mnist = fetch_openml('mnist_784', as_frame= False)
x = mnist['data']
y = mnist['target']

In [16]:
print(x)
print(x.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(70000, 784)


In [17]:
print(y)
print(y.shape)

['5' '0' '4' ... '4' '5' '6']
(70000,)
